// Command genwalker generates walk_generated.go from parsenodes.go.
//
// It scans all struct types in parsenodes.go and node.go, identifies fields
// whose types are Node (interface), *List, or pointers to other AST structs,
// and generates the walkChildren function that enumerates child nodes for Walk.
//
// Usage:
//
//	go run ./pg/ast/cmd/genwalker
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func main() {
	fset := token.NewFileSet()

	// Parse both source files.
	sources := []string{"parsenodes.go", "node.go"}
	var files []*ast.File
	for _, src := range sources {
		f, err := parser.ParseFile(fset, src, nil, 0)
		if err != nil {
			fmt.Fprintf(os.Stderr, "parse %s: %v\n", src, err)
			os.Exit(1)
		}
		files = append(files, f)
	}

	// Collect all struct type names.
	structNames := map[string]bool{}
	type field struct {
		Name string
		Type string // "Node", "*List", "*SelectStmt", etc.
	}
	type structInfo struct {
		Name   string
		Fields []field
	}

	var structs []structInfo

	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				if _, ok := ts.Type.(*ast.StructType); ok {
					structNames[ts.Name.Name] = true
				}
			}
		}
	}

	// Now collect fields for each struct.
	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				var fields []field
				for _, f := range st.Fields.List {
					if len(f.Names) == 0 {
						continue // embedded
					}
					typStr := typeString(f.Type)
					if isChildType(typStr, structNames) {
						for _, name := range f.Names {
							fields = append(fields, field{Name: name.Name, Type: typStr})
						}
					}
				}
				structs = append(structs, structInfo{Name: ts.Name.Name, Fields: fields})
			}
		}
	}

	// Sort by name for deterministic output.
	sort.Slice(structs, func(i, j int) bool {
		return structs[i].Name < structs[j].Name
	})

	// Generate code.
	var buf bytes.Buffer
	buf.WriteString("// Code generated by genwalker; DO NOT EDIT.\n\n")
	buf.WriteString("package ast\n\n")
	buf.WriteString("// walkChildren walks the child nodes of node, calling Walk(v, child)\n")
	buf.WriteString("// for each child. This function is generated from parsenodes.go.\n")
	buf.WriteString("func walkChildren(v Visitor, node Node) {\n")
	buf.WriteString("\tswitch n := node.(type) {\n")

	for _, s := range structs {
		if len(s.Fields) == 0 {
			continue
		}
		fmt.Fprintf(&buf, "\tcase *%s:\n", s.Name)
		for _, f := range s.Fields {
			switch {
			case f.Type == "Node":
				fmt.Fprintf(&buf, "\t\tWalk(v, n.%s)\n", f.Name)
			case f.Type == "*List":
				fmt.Fprintf(&buf, "\t\twalkList(v, n.%s)\n", f.Name)
			default:
				// Pointer to a known struct type (e.g. *RangeVar)
				fmt.Fprintf(&buf, "\t\tif n.%s != nil {\n", f.Name)
				fmt.Fprintf(&buf, "\t\t\tWalk(v, n.%s)\n", f.Name)
				fmt.Fprintf(&buf, "\t\t}\n")
			}
		}
	}

	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	// Format.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		// Write unformatted for debugging.
		os.WriteFile("walk_generated.go", buf.Bytes(), 0644)
		os.Exit(1)
	}

	if err := os.WriteFile("walk_generated.go", formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	// Stats.
	cases := 0
	fields := 0
	for _, s := range structs {
		if len(s.Fields) > 0 {
			cases++
			fields += len(s.Fields)
		}
	}
	fmt.Printf("Generated walk_generated.go: %d cases, %d child fields\n", cases, fields)
}

// typeString returns the string representation of a Go type expression.
func typeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		return "[]" + typeString(t.Elt)
	default:
		return ""
	}
}

// isChildType returns true if typStr represents a child node field.
func isChildType(typStr string, structNames map[string]bool) bool {
	if typStr == "Node" {
		return true
	}
	if typStr == "*List" {
		return true
	}
	if strings.HasPrefix(typStr, "*") {
		name := typStr[1:]
		// Exclude non-node structs.
		if name == "IntList" || name == "OidList" || name == "Loc" {
			return false
		}
		return structNames[name]
	}
	return false
}
