// Code generated by genwalker; DO NOT EDIT.

package ast

// walkChildren walks the child nodes of node, calling Walk(v, child)
// for each child. This function is generated from parsenodes.go.
func walkChildren(v Visitor, node Node) {
	switch n := node.(type) {
	case *AlterDatabaseStmt:
		for _, item := range n.Options {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterEventStmt:
		if n.Schedule != nil {
			Walk(v, n.Schedule)
		}
	case *AlterRoutineStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Characteristics {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterTableCmd:
		if n.Column != nil {
			Walk(v, n.Column)
		}
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Constraint != nil {
			Walk(v, n.Constraint)
		}
		if n.Option != nil {
			Walk(v, n.Option)
		}
		Walk(v, n.DefaultExpr)
		for _, item := range n.PartitionDefs {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.ExchangeTable != nil {
			Walk(v, n.ExchangeTable)
		}
		for _, item := range n.OrderByItems {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.PartitionBy != nil {
			Walk(v, n.PartitionBy)
		}
	case *AlterTableStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, item := range n.Commands {
			if item != nil {
				Walk(v, item)
			}
		}
	case *AlterUserStmt:
		for _, item := range n.Users {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Require != nil {
			Walk(v, n.Require)
		}
		if n.Resource != nil {
			Walk(v, n.Resource)
		}
		for _, item := range n.FactorOps {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.RegistrationOp != nil {
			Walk(v, n.RegistrationOp)
		}
	case *AlterViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Select != nil {
			Walk(v, n.Select)
		}
	case *AnalyzeTableStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *Assignment:
		if n.Column != nil {
			Walk(v, n.Column)
		}
		Walk(v, n.Value)
	case *BeginEndBlock:
		for _, item := range n.Stmts {
			Walk(v, item)
		}
	case *BetweenExpr:
		Walk(v, n.Expr)
		Walk(v, n.Low)
		Walk(v, n.High)
	case *BinaryExpr:
		Walk(v, n.Left)
		Walk(v, n.Right)
	case *CacheIndexStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CallStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Args {
			Walk(v, item)
		}
	case *CaseExpr:
		Walk(v, n.Operand)
		for _, item := range n.Whens {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.Default)
	case *CaseStmtNode:
		Walk(v, n.Operand)
		for _, item := range n.Whens {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.ElseList {
			Walk(v, item)
		}
	case *CaseStmtWhen:
		Walk(v, n.Cond)
		for _, item := range n.ThenList {
			Walk(v, item)
		}
	case *CaseWhen:
		Walk(v, n.Cond)
		Walk(v, n.Result)
	case *CastExpr:
		Walk(v, n.Expr)
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	case *ChangeReplicationFilterStmt:
		for _, item := range n.Filters {
			if item != nil {
				Walk(v, item)
			}
		}
	case *ChangeReplicationSourceStmt:
		for _, item := range n.Options {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CheckTableStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *ChecksumTableStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CollateExpr:
		Walk(v, n.Expr)
	case *ColumnConstraint:
		Walk(v, n.Expr)
		if n.RefTable != nil {
			Walk(v, n.RefTable)
		}
	case *ColumnDef:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		for _, item := range n.Constraints {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.DefaultValue)
		Walk(v, n.OnUpdate)
		if n.Generated != nil {
			Walk(v, n.Generated)
		}
	case *CommonTableExpr:
		if n.Select != nil {
			Walk(v, n.Select)
		}
	case *Constraint:
		for _, item := range n.IndexColumns {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.IndexOptions {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.Expr)
		if n.RefTable != nil {
			Walk(v, n.RefTable)
		}
	case *ConvertExpr:
		Walk(v, n.Expr)
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	case *CreateDatabaseStmt:
		for _, item := range n.Options {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreateEventStmt:
		if n.Schedule != nil {
			Walk(v, n.Schedule)
		}
	case *CreateFunctionStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		for _, item := range n.Params {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Returns != nil {
			Walk(v, n.Returns)
		}
		for _, item := range n.Characteristics {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreateIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Options {
			if item != nil {
				Walk(v, item)
			}
		}
	case *CreateTableStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Constraints {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Options {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Partitions != nil {
			Walk(v, n.Partitions)
		}
		if n.Like != nil {
			Walk(v, n.Like)
		}
		if n.Select != nil {
			Walk(v, n.Select)
		}
	case *CreateTriggerStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		if n.Order != nil {
			Walk(v, n.Order)
		}
	case *CreateUserStmt:
		for _, item := range n.Users {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Require != nil {
			Walk(v, n.Require)
		}
		if n.Resource != nil {
			Walk(v, n.Resource)
		}
	case *CreateViewStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
		if n.Select != nil {
			Walk(v, n.Select)
		}
	case *DeclareCursorStmt:
		if n.Select != nil {
			Walk(v, n.Select)
		}
	case *DeclareHandlerStmt:
		Walk(v, n.Stmt)
	case *DeclareVarStmt:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		Walk(v, n.Default)
	case *DeleteStmt:
		for _, item := range n.Tables {
			Walk(v, item)
		}
		for _, item := range n.Using {
			Walk(v, item)
		}
		Walk(v, n.Where)
		for _, item := range n.OrderBy {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Limit != nil {
			Walk(v, n.Limit)
		}
	case *DiagnosticsItem:
		Walk(v, n.Target)
	case *DoStmt:
		for _, item := range n.Exprs {
			Walk(v, item)
		}
	case *DropIndexStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *DropRoutineStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropTableStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *DropTriggerStmt:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *DropViewStmt:
		for _, item := range n.Views {
			if item != nil {
				Walk(v, item)
			}
		}
	case *ElseIf:
		Walk(v, n.Cond)
		for _, item := range n.ThenList {
			Walk(v, item)
		}
	case *EventSchedule:
		Walk(v, n.At)
		Walk(v, n.Every)
		Walk(v, n.Starts)
		Walk(v, n.Ends)
	case *ExecuteStmt:
		for _, item := range n.Params {
			Walk(v, item)
		}
	case *ExistsExpr:
		if n.Select != nil {
			Walk(v, n.Select)
		}
	case *ExplainStmt:
		Walk(v, n.Stmt)
	case *ExtractExpr:
		Walk(v, n.Expr)
	case *FlushStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *ForUpdate:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *FuncCallExpr:
		for _, item := range n.Args {
			Walk(v, item)
		}
		for _, item := range n.OrderBy {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Over != nil {
			Walk(v, n.Over)
		}
		Walk(v, n.Separator)
	case *FuncParam:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
	case *GeneratedColumn:
		Walk(v, n.Expr)
	case *GetDiagnosticsStmt:
		Walk(v, n.ConditionNumber)
		for _, item := range n.Items {
			if item != nil {
				Walk(v, item)
			}
		}
	case *GrantStmt:
		if n.On != nil {
			Walk(v, n.On)
		}
		if n.Require != nil {
			Walk(v, n.Require)
		}
		if n.Resource != nil {
			Walk(v, n.Resource)
		}
	case *GrantTarget:
		if n.Name != nil {
			Walk(v, n.Name)
		}
	case *HandlerCloseStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *HandlerOpenStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *HandlerReadStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		Walk(v, n.Where)
		if n.Limit != nil {
			Walk(v, n.Limit)
		}
	case *IfStmt:
		Walk(v, n.Cond)
		for _, item := range n.ThenList {
			Walk(v, item)
		}
		for _, item := range n.ElseIfs {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.ElseList {
			Walk(v, item)
		}
	case *InExpr:
		Walk(v, n.Expr)
		for _, item := range n.List {
			Walk(v, item)
		}
		if n.Select != nil {
			Walk(v, n.Select)
		}
	case *IndexColumn:
		Walk(v, n.Expr)
	case *IndexOption:
		Walk(v, n.Value)
	case *InsertStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Select != nil {
			Walk(v, n.Select)
		}
		if n.TableSource != nil {
			Walk(v, n.TableSource)
		}
		for _, item := range n.SetList {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.OnDuplicateKey {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.Returning {
			Walk(v, item)
		}
	case *InstallComponentStmt:
		for _, item := range n.SetVars {
			if item != nil {
				Walk(v, item)
			}
		}
	case *IntervalExpr:
		Walk(v, n.Value)
	case *IntoClause:
		for _, item := range n.Vars {
			if item != nil {
				Walk(v, item)
			}
		}
	case *IsExpr:
		Walk(v, n.Expr)
	case *JoinClause:
		Walk(v, n.Left)
		Walk(v, n.Right)
		Walk(v, n.Condition)
	case *JsonTableColumn:
		if n.TypeName != nil {
			Walk(v, n.TypeName)
		}
		for _, item := range n.NestedCols {
			if item != nil {
				Walk(v, item)
			}
		}
	case *JsonTableExpr:
		Walk(v, n.Expr)
		Walk(v, n.Path)
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
	case *KillStmt:
		Walk(v, n.ConnectionID)
	case *LikeExpr:
		Walk(v, n.Expr)
		Walk(v, n.Pattern)
		Walk(v, n.Escape)
	case *Limit:
		Walk(v, n.Count)
		Walk(v, n.Offset)
	case *List:
		for _, item := range n.Items {
			Walk(v, item)
		}
	case *LoadDataStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.SetList {
			if item != nil {
				Walk(v, item)
			}
		}
	case *LoadIndexIntoCacheStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *LoadIndexTable:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *LockTable:
		if n.Table != nil {
			Walk(v, n.Table)
		}
	case *LockTablesStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *LoopStmt:
		for _, item := range n.Stmts {
			Walk(v, item)
		}
	case *MatchExpr:
		for _, item := range n.Columns {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.Against)
	case *MemberOfExpr:
		Walk(v, n.Value)
		Walk(v, n.Array)
	case *OnCondition:
		Walk(v, n.Expr)
	case *OptimizeTableStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *OrderByItem:
		Walk(v, n.Expr)
	case *ParenExpr:
		Walk(v, n.Expr)
	case *PartitionClause:
		Walk(v, n.Expr)
		for _, item := range n.Partitions {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.SubPartExpr)
	case *PartitionDef:
		Walk(v, n.Values)
		for _, item := range n.Options {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.SubPartitions {
			if item != nil {
				Walk(v, item)
			}
		}
	case *PurgeBinaryLogsStmt:
		Walk(v, n.BeforeExpr)
	case *RawStmt:
		Walk(v, n.Stmt)
	case *RenameTablePair:
		if n.Old != nil {
			Walk(v, n.Old)
		}
		if n.New != nil {
			Walk(v, n.New)
		}
	case *RenameTableStmt:
		for _, item := range n.Pairs {
			if item != nil {
				Walk(v, item)
			}
		}
	case *RenameUserStmt:
		for _, item := range n.Pairs {
			if item != nil {
				Walk(v, item)
			}
		}
	case *RepairTableStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *RepeatStmt:
		for _, item := range n.Stmts {
			Walk(v, item)
		}
		Walk(v, n.Cond)
	case *ResTarget:
		Walk(v, n.Val)
	case *ResignalStmt:
		for _, item := range n.SetItems {
			if item != nil {
				Walk(v, item)
			}
		}
	case *ReturnStmt:
		Walk(v, n.Expr)
	case *RevokeStmt:
		if n.On != nil {
			Walk(v, n.On)
		}
	case *RowExpr:
		for _, item := range n.Items {
			Walk(v, item)
		}
	case *SelectStmt:
		for _, item := range n.CTEs {
			if item != nil {
				Walk(v, item)
			}
		}
		for _, item := range n.TargetList {
			Walk(v, item)
		}
		for _, item := range n.From {
			Walk(v, item)
		}
		Walk(v, n.Where)
		for _, item := range n.GroupBy {
			Walk(v, item)
		}
		Walk(v, n.Having)
		for _, item := range n.OrderBy {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Limit != nil {
			Walk(v, n.Limit)
		}
		if n.ForUpdate != nil {
			Walk(v, n.ForUpdate)
		}
		for _, item := range n.WindowClause {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Into != nil {
			Walk(v, n.Into)
		}
		if n.Left != nil {
			Walk(v, n.Left)
		}
		if n.Right != nil {
			Walk(v, n.Right)
		}
	case *SetPasswordStmt:
		if n.User != nil {
			Walk(v, n.User)
		}
	case *SetStmt:
		for _, item := range n.Assignments {
			if item != nil {
				Walk(v, item)
			}
		}
	case *ShowStmt:
		if n.From != nil {
			Walk(v, n.From)
		}
		Walk(v, n.Like)
		Walk(v, n.Where)
		Walk(v, n.ForQuery)
		if n.ForUser != nil {
			Walk(v, n.ForUser)
		}
		for _, item := range n.Using {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.FromPos)
		Walk(v, n.LimitCount)
		Walk(v, n.LimitOffset)
	case *SignalInfoItem:
		Walk(v, n.Value)
	case *SignalStmt:
		for _, item := range n.SetItems {
			if item != nil {
				Walk(v, item)
			}
		}
	case *SubPartitionDef:
		for _, item := range n.Options {
			if item != nil {
				Walk(v, item)
			}
		}
	case *SubqueryExpr:
		if n.Select != nil {
			Walk(v, n.Select)
		}
	case *TableRef:
		for _, item := range n.IndexHints {
			if item != nil {
				Walk(v, item)
			}
		}
	case *TableStmt:
		if n.Table != nil {
			Walk(v, n.Table)
		}
		for _, item := range n.OrderBy {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Limit != nil {
			Walk(v, n.Limit)
		}
		if n.Into != nil {
			Walk(v, n.Into)
		}
	case *TruncateStmt:
		for _, item := range n.Tables {
			if item != nil {
				Walk(v, item)
			}
		}
	case *UnaryExpr:
		Walk(v, n.Operand)
	case *UpdateStmt:
		for _, item := range n.Tables {
			Walk(v, item)
		}
		for _, item := range n.SetList {
			if item != nil {
				Walk(v, item)
			}
		}
		Walk(v, n.Where)
		for _, item := range n.OrderBy {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Limit != nil {
			Walk(v, n.Limit)
		}
	case *UserSpec:
		for _, item := range n.AuthFactors {
			if item != nil {
				Walk(v, item)
			}
		}
	case *ValuesStmt:
		for _, item := range n.OrderBy {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Limit != nil {
			Walk(v, n.Limit)
		}
	case *WhileStmt:
		Walk(v, n.Cond)
		for _, item := range n.Stmts {
			Walk(v, item)
		}
	case *WindowDef:
		for _, item := range n.PartitionBy {
			Walk(v, item)
		}
		for _, item := range n.OrderBy {
			if item != nil {
				Walk(v, item)
			}
		}
		if n.Frame != nil {
			Walk(v, n.Frame)
		}
	case *WindowFrame:
		if n.Start != nil {
			Walk(v, n.Start)
		}
		if n.End != nil {
			Walk(v, n.End)
		}
	case *WindowFrameBound:
		Walk(v, n.Offset)
	case *XAStmt:
		for _, item := range n.Xid {
			Walk(v, item)
		}
	}
}
