package catalog

import (
	"fmt"
	"sort"
)

// generateColumnDDL produces ALTER TABLE … ADD/DROP/ALTER COLUMN operations
// for every column change within modified relations.
func generateColumnDDL(from, to *Catalog, diff *SchemaDiff) []MigrationOp {
	var ops []MigrationOp

	for _, rel := range diff.Relations {
		if rel.Action != DiffModify {
			continue
		}
		if len(rel.Columns) == 0 {
			continue
		}

		tableName := fmt.Sprintf("%s.%s", quoteIdentifier(rel.SchemaName), quoteIdentifier(rel.Name))

		for _, col := range rel.Columns {
			switch col.Action {
			case DiffAdd:
				ops = append(ops, columnAddOps(to, tableName, rel.SchemaName, rel.Name, col)...)
			case DiffDrop:
				ops = append(ops, MigrationOp{
					Type:          OpDropColumn,
					SchemaName:    rel.SchemaName,
					ObjectName:    rel.Name,
					SQL:           fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", tableName, quoteIdentifier(col.Name)),
					Transactional: true,
				})
			case DiffModify:
				ops = append(ops, columnModifyOps(from, to, tableName, rel.SchemaName, rel.Name, col)...)
			}
		}
	}

	// Determinism is ensured by iterating relations (sorted in diff) and
	// columns (sorted by name in diff). Within a single column's modifications,
	// the insertion order matters (e.g., DROP DEFAULT → ALTER TYPE → SET DEFAULT),
	// so we use stable sort by schema+table only.
	sort.SliceStable(ops, func(i, j int) bool {
		if ops[i].SchemaName != ops[j].SchemaName {
			return ops[i].SchemaName < ops[j].SchemaName
		}
		return ops[i].ObjectName < ops[j].ObjectName
	})

	return ops
}

// columnAddOps generates an ALTER TABLE … ADD COLUMN statement.
func columnAddOps(to *Catalog, tableName, schemaName, relName string, col ColumnDiffEntry) []MigrationOp {
	c := col.To
	typeName := to.FormatType(c.TypeOID, c.TypeMod)

	ddl := fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", tableName, quoteIdentifier(c.Name), typeName)

	if c.NotNull {
		ddl += " NOT NULL"
	}
	if c.HasDefault && c.Default != "" {
		ddl += " DEFAULT " + c.Default
	}
	if c.Identity != 0 {
		switch c.Identity {
		case 'a':
			ddl += " GENERATED ALWAYS AS IDENTITY"
		case 'd':
			ddl += " GENERATED BY DEFAULT AS IDENTITY"
		}
	}
	if c.Generated == 's' && c.GenerationExpr != "" {
		ddl += " GENERATED ALWAYS AS (" + c.GenerationExpr + ") STORED"
	}

	return []MigrationOp{{
		Type:          OpAddColumn,
		SchemaName:    schemaName,
		ObjectName:    relName,
		SQL:           ddl,
		Transactional: true,
	}}
}

// columnModifyOps generates ALTER TABLE … ALTER COLUMN statements for a
// modified column. Multiple property changes on the same column produce
// multiple ALTER statements; when a type change is combined with an existing
// default, the sequence is DROP DEFAULT → ALTER TYPE → SET DEFAULT.
func columnModifyOps(from, to *Catalog, tableName, schemaName, relName string, col ColumnDiffEntry) []MigrationOp {
	oldCol := col.From
	newCol := col.To
	var ops []MigrationOp

	colRef := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s", tableName, quoteIdentifier(newCol.Name))

	typeChanged := from.FormatType(oldCol.TypeOID, oldCol.TypeMod) != to.FormatType(newCol.TypeOID, newCol.TypeMod)

	// When type changes and the old column has a default, we must drop the
	// default first, then change the type, then re-set the new default.
	needDefaultSandwich := typeChanged && oldCol.HasDefault && oldCol.Default != ""

	// --- DROP DEFAULT before type change (if sandwich) ---
	if needDefaultSandwich {
		ops = append(ops, MigrationOp{
			Type:          OpAlterColumn,
			SchemaName:    schemaName,
			ObjectName:    relName,
			SQL:           fmt.Sprintf("%s DROP DEFAULT", colRef),
			Transactional: true,
		})
	}

	// --- Type change ---
	if typeChanged {
		newType := to.FormatType(newCol.TypeOID, newCol.TypeMod)
		alterType := fmt.Sprintf("%s TYPE %s", colRef, newType)

		// Check if an implicit (assignment) cast exists.
		pathway, _ := from.FindCoercionPathway(oldCol.TypeOID, newCol.TypeOID, 'a')
		if pathway == CoercionNone {
			// Need explicit USING clause.
			alterType += fmt.Sprintf(" USING %s::%s", quoteIdentifier(newCol.Name), newType)
		}

		ops = append(ops, MigrationOp{
			Type:          OpAlterColumn,
			SchemaName:    schemaName,
			ObjectName:    relName,
			SQL:           alterType,
			Transactional: true,
		})
	}

	// --- SET DEFAULT after type change (if sandwich) ---
	if needDefaultSandwich && newCol.HasDefault && newCol.Default != "" {
		ops = append(ops, MigrationOp{
			Type:          OpAlterColumn,
			SchemaName:    schemaName,
			ObjectName:    relName,
			SQL:           fmt.Sprintf("%s SET DEFAULT %s", colRef, newCol.Default),
			Transactional: true,
		})
	}

	// --- Default change (without type change) ---
	if !needDefaultSandwich && !typeChanged {
		if oldCol.HasDefault && !newCol.HasDefault {
			ops = append(ops, MigrationOp{
				Type:          OpAlterColumn,
				SchemaName:    schemaName,
				ObjectName:    relName,
				SQL:           fmt.Sprintf("%s DROP DEFAULT", colRef),
				Transactional: true,
			})
		} else if newCol.HasDefault && newCol.Default != "" && (oldCol.Default != newCol.Default || !oldCol.HasDefault) {
			ops = append(ops, MigrationOp{
				Type:          OpAlterColumn,
				SchemaName:    schemaName,
				ObjectName:    relName,
				SQL:           fmt.Sprintf("%s SET DEFAULT %s", colRef, newCol.Default),
				Transactional: true,
			})
		}
	}

	// --- NOT NULL change ---
	if oldCol.NotNull != newCol.NotNull {
		if newCol.NotNull {
			ops = append(ops, MigrationOp{
				Type:          OpAlterColumn,
				SchemaName:    schemaName,
				ObjectName:    relName,
				SQL:           fmt.Sprintf("%s SET NOT NULL", colRef),
				Transactional: true,
			})
		} else {
			ops = append(ops, MigrationOp{
				Type:          OpAlterColumn,
				SchemaName:    schemaName,
				ObjectName:    relName,
				SQL:           fmt.Sprintf("%s DROP NOT NULL", colRef),
				Transactional: true,
			})
		}
	}

	// --- Identity change ---
	if oldCol.Identity != newCol.Identity {
		if newCol.Identity == 'a' {
			ops = append(ops, MigrationOp{
				Type:          OpAlterColumn,
				SchemaName:    schemaName,
				ObjectName:    relName,
				SQL:           fmt.Sprintf("%s ADD GENERATED ALWAYS AS IDENTITY", colRef),
				Transactional: true,
			})
		} else if newCol.Identity == 'd' {
			ops = append(ops, MigrationOp{
				Type:          OpAlterColumn,
				SchemaName:    schemaName,
				ObjectName:    relName,
				SQL:           fmt.Sprintf("%s ADD GENERATED BY DEFAULT AS IDENTITY", colRef),
				Transactional: true,
			})
		} else if oldCol.Identity != 0 && newCol.Identity == 0 {
			ops = append(ops, MigrationOp{
				Type:          OpAlterColumn,
				SchemaName:    schemaName,
				ObjectName:    relName,
				SQL:           fmt.Sprintf("%s DROP IDENTITY", colRef),
				Transactional: true,
			})
		}
	}

	return ops
}
