package catalog

import (
	"sort"
	"strings"
)

// ---------------------------------------------------------------------------
// pg_catalog system table row types
//
// Each struct mirrors the columns of the corresponding PG system table.
// Query methods iterate in-memory catalog state and return rows.
//
// pg: src/include/catalog/pg_*.h
// ---------------------------------------------------------------------------

// PgNamespaceRow mirrors pg_namespace.
type PgNamespaceRow struct {
	OID     uint32
	NspName string
}

// PgClassRow mirrors pg_class (subset of columns relevant to DDL).
type PgClassRow struct {
	OID             uint32
	RelName         string
	RelNamespace    uint32
	RelType         uint32 // composite type OID
	RelKind         byte   // 'r', 'v', 'i', 'S'
	RelNatts        int16
	RelChecks       int16
	RelHasTriggers  bool
	RelHasIndex     bool
	RelPersistence  byte   // 'p'=permanent, 'u'=unlogged, 't'=temp
	ReplicaIdentity byte   // 'd'=default, 'f'=full, 'n'=nothing, 'i'=index
	RelOfType          uint32 // reloftype — 0 if not a typed table
	RelRowSecurity     bool   // relrowsecurity
	RelForceRowSecurity bool  // relforcerowsecurity
}

// PgAttributeRow mirrors pg_attribute.
type PgAttributeRow struct {
	AttRelID     uint32
	AttName      string
	AttTypID     uint32
	AttNum       int16
	AttTypMod    int32
	AttLen       int16
	AttByVal     bool
	AttAlign     byte
	AttStorage   byte
	AttNotNull   bool
	AttHasDef    bool
	AttIsDropped bool
	AttCollation uint32
	AttGenerated byte // 's' = stored generated, 0 = none
	AttIdentity  byte // 'a' = ALWAYS, 'd' = BY DEFAULT, 0 = none
	AttIsLocal   bool // true if defined locally
	AttInhCount  int  // number of inheritance ancestors
}

// PgTypeRow mirrors pg_type.
type PgTypeRow struct {
	OID          uint32
	TypName      string
	TypNamespace uint32
	TypLen       int16
	TypByVal     bool
	TypType      byte // 'b', 'c', 'd', 'e'
	TypCategory  byte
	TypIsDefined bool
	TypDelim     byte
	TypRelID     uint32 // for composite types
	TypElem      uint32 // array element type
	TypArray     uint32 // corresponding array type
	TypBaseType  uint32 // for domains
	TypTypMod    int32
	TypAlign     byte
	TypStorage   byte
	TypNotNull   bool
	TypCollation uint32
}

// PgConstraintRow mirrors pg_constraint.
type PgConstraintRow struct {
	OID           uint32
	ConName       string
	ConNamespace  uint32
	ConType       byte // 'c', 'f', 'p', 'u'
	ConRelID      uint32
	ConTypID      uint32  // for domain constraints
	ConKey        []int16 // constrained columns
	ConFRelID     uint32  // FK: referenced relation
	ConFKey       []int16 // FK: referenced columns
	ConFUpdType   byte    // FK: ON UPDATE action
	ConFDelType   byte    // FK: ON DELETE action
	ConFMatchType byte    // FK: match type
	ConDeferrable bool
	ConDeferred   bool
	ConValidated  bool
	ConIndexID    uint32 // backing index (PK/UNIQUE)
	ConExpr       string // CHECK expression text

	// Inheritance/partition fields.
	ConParentID  uint32 // parent constraint OID
	ConIsLocal   bool   // locally defined
	ConInhCount  int16  // inheritance count
	ConNoInherit bool   // cannot be inherited

	// FK operator arrays.
	PFEqOp       []uint32 // PK=FK equality operators
	PPEqOp       []uint32 // PK=PK equality operators
	FFEqOp       []uint32 // FK=FK equality operators
	FKDelSetCols []int16  // ON DELETE SET NULL/DEFAULT column subset
}

// PgIndexRow mirrors pg_index.
type PgIndexRow struct {
	IndexRelID     uint32
	IndRelID       uint32
	IndNatts       int16
	IndNKeyAtts    int16
	IndIsUnique    bool
	IndIsPrimary   bool
	IndIsClustered bool
	IndIsReplIdent bool
	IndKey         []int16
	IndOption      []int16
	IndExprs       string // deparsed expression text (pg_get_expr format)
	IndPred        string // WHERE clause text (pg_get_expr format)
}

// PgSequenceRow mirrors pg_sequence.
type PgSequenceRow struct {
	SeqRelID     uint32
	SeqTypID     uint32
	SeqStart     int64
	SeqIncrement int64
	SeqMax       int64
	SeqMin       int64
	SeqCache     int64
	SeqCycle     bool
}

// PgEnumRow mirrors pg_enum.
type PgEnumRow struct {
	OID           uint32
	EnumTypID     uint32
	EnumSortOrder float32
	EnumLabel     string
}

// PgInheritsRow mirrors pg_inherits.
type PgInheritsRow struct {
	InhRelID  uint32 // child relation OID
	InhParent uint32 // parent relation OID
	InhSeqNo  int32  // order in INHERITS list (1-based)
}

// PgDependRow mirrors pg_depend.
//
// pg: src/include/catalog/pg_depend.h
type PgDependRow struct {
	ClassID    uint32
	ObjID      uint32
	ObjSubID   int32
	RefClassID uint32
	RefObjID   uint32
	RefSubID   int32
	DepType    byte
}

// PgDescriptionRow mirrors pg_description.
type PgDescriptionRow struct {
	ObjOID      uint32
	ClassOID    uint32
	ObjSubID    int16
	Description string
}

// PgAttrdefRow mirrors pg_attrdef.
type PgAttrdefRow struct {
	OID     uint32
	AdRelID uint32
	AdNum   int16
	AdBin   string // pg_get_expr(adbin) text
}

// PgTriggerRow mirrors pg_trigger.
type PgTriggerRow struct {
	OID        uint32
	TgRelID    uint32
	TgName     string
	TgFOID     uint32
	TgType     int16
	TgEnabled  byte
	TgAttr     []int16
	TgQual     string // WHEN clause expression (pg_get_expr format)
	TgOldTable string // OLD TABLE AS transition table name
	TgNewTable string // NEW TABLE AS transition table name
}

// PgProcRow mirrors pg_proc (user-created only).
type PgProcRow struct {
	OID             uint32
	ProName         string
	ProNamespace    uint32
	ProKind         byte // 'f', 'p'
	ProArgTypes     []uint32
	ProRetType      uint32
	ProRetSet       bool
	ProIsStrict     bool
	ProVolatile     byte
	ProParallel     byte
	ProSecDef       bool
	ProLeakProof    bool
	ProLang         string   // language name
	ProSrc          string   // function body
	ProArgNames     []string // all parameter names; nil if no names
	ProArgModes     []byte   // parameter modes; nil if all IN
	ProAllArgTypes  []uint32 // all parameter types; nil if no OUT params
	ProNArgDefaults int16    // number of parameters with defaults
}

// ---------------------------------------------------------------------------
// Catalog class OID constants (pg_class OIDs for system tables)
// ---------------------------------------------------------------------------

const (
	RelationRelationID   uint32 = 1259 // pg_class
	TypeRelationID       uint32 = 1247 // pg_type
	ConstraintRelationID uint32 = 2606 // pg_constraint
	ProcedureRelationID  uint32 = 1255 // pg_proc
	TriggerRelationID    uint32 = 2620 // pg_trigger
	NamespaceRelationID  uint32 = 2615 // pg_namespace
	IndexRelationID      uint32 = 2610 // pg_index (catalog, not the index itself)
	AttrDefaultRelID     uint32 = 2604 // pg_attrdef
	SequenceRelationID   uint32 = 2224 // pg_sequence_rel (class of seq relations is pg_class)
)

// ---------------------------------------------------------------------------
// Query methods
// ---------------------------------------------------------------------------

// QueryPgNamespace returns all user-created schemas as pg_namespace rows.
//
// (pgddl helper — PG uses ScanPgRelation/SearchSysCache with pg_namespace)
func (c *Catalog) QueryPgNamespace() []PgNamespaceRow {
	var rows []PgNamespaceRow
	for _, s := range c.schemaByName {
		// Skip built-in schemas.
		if s.OID < FirstNormalObjectId && s.OID != PublicNamespace {
			continue
		}
		rows = append(rows, PgNamespaceRow{
			OID:     s.OID,
			NspName: s.Name,
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].OID < rows[j].OID })
	return rows
}

// QueryPgClass returns pg_class rows for all objects in the given schema.
//
// (pgddl helper — PG uses ScanPgRelation/SearchSysCache with pg_class)
func (c *Catalog) QueryPgClass(schemaName string) []PgClassRow {
	schema := c.schemaByName[schemaName]
	if schema == nil {
		return nil
	}

	var rows []PgClassRow

	// Relations (tables and views).
	for _, rel := range schema.Relations {
		persistence := rel.Persistence
		if persistence == 0 {
			persistence = 'p'
		}
		replicaIdentity := rel.ReplicaIdentity
		if replicaIdentity == 0 {
			switch rel.RelKind {
			case 'v', 'c':
				replicaIdentity = 'n' // views and composite types: nothing
			default:
				replicaIdentity = 'd' // tables and matviews: default
			}
		}
		row := PgClassRow{
			OID:                rel.OID,
			RelName:            rel.Name,
			RelNamespace:       schema.OID,
			RelType:            rel.RowTypeOID,
			RelKind:            rel.RelKind,
			RelNatts:           int16(len(rel.Columns)),
			RelPersistence:     persistence,
			ReplicaIdentity:    replicaIdentity,
			RelOfType:          rel.OfTypeOID,
			RelRowSecurity:     rel.RowSecurity,
			RelForceRowSecurity: rel.ForceRowSecurity,
		}

		// Count CHECK constraints.
		for _, con := range c.consByRel[rel.OID] {
			if con.Type == ConstraintCheck {
				row.RelChecks++
			}
		}

		// Has triggers?
		if len(c.triggersByRel[rel.OID]) > 0 {
			row.RelHasTriggers = true
		}

		// PG creates implicit RI triggers for FK constraints.
		// pg: src/backend/commands/tablecmds.c — CreateFKCheckTrigger, createForeignKeyActionTriggers
		if !row.RelHasTriggers {
			for _, con := range c.consByRel[rel.OID] {
				if con.Type == ConstraintFK {
					row.RelHasTriggers = true
					break
				}
			}
		}
		// Also check if this relation is referenced by FK constraints from other tables.
		if !row.RelHasTriggers {
			for _, cons := range c.consByRel {
				for _, con := range cons {
					if con.Type == ConstraintFK && con.FRelOID == rel.OID {
						row.RelHasTriggers = true
						break
					}
				}
				if row.RelHasTriggers {
					break
				}
			}
		}

		// Has indexes?
		if len(c.indexesByRel[rel.OID]) > 0 {
			row.RelHasIndex = true
		}

		rows = append(rows, row)
	}

	// Indexes (relkind='i').
	for _, idx := range schema.Indexes {
		row := PgClassRow{
			OID:             idx.OID,
			RelName:         idx.Name,
			RelNamespace:    schema.OID,
			RelKind:         'i',
			RelNatts:        int16(len(idx.Columns)),
			RelPersistence:  'p',
			ReplicaIdentity: 'n', // indexes always 'n' (nothing)
		}
		rows = append(rows, row)
	}

	// Sequences (relkind='S').
	for _, seq := range schema.Sequences {
		row := PgClassRow{
			OID:             seq.OID,
			RelName:         seq.Name,
			RelNamespace:    schema.OID,
			RelKind:         'S',
			RelNatts:        3, // PG sequences always have 3 columns (last_value, log_cnt, is_called)
			RelPersistence:  'p',
			ReplicaIdentity: 'n', // sequences always 'n' (nothing)
		}
		rows = append(rows, row)
	}

	sort.Slice(rows, func(i, j int) bool { return rows[i].OID < rows[j].OID })
	return rows
}

// QueryPgAttribute returns pg_attribute rows for a relation by OID.
//
// (pgddl helper — PG uses ScanPgRelation/SearchSysCache with pg_attribute)
func (c *Catalog) QueryPgAttribute(relOID uint32) []PgAttributeRow {
	rel := c.relationByOID[relOID]
	if rel == nil {
		return nil
	}

	rows := make([]PgAttributeRow, len(rel.Columns))
	for i, col := range rel.Columns {
		hasDef := col.HasDefault
		notNull := col.NotNull
		// PG: identity columns are NOT tracked via atthasdef; identity implies NOT NULL.
		// pg: src/backend/catalog/heap.c — identity handling
		if col.Identity != 0 {
			hasDef = false
			notNull = true
		}
		rows[i] = PgAttributeRow{
			AttRelID:     relOID,
			AttName:      col.Name,
			AttTypID:     col.TypeOID,
			AttNum:       col.AttNum,
			AttTypMod:    col.TypeMod,
			AttLen:       col.Len,
			AttByVal:     col.ByVal,
			AttAlign:     col.Align,
			AttStorage:   col.Storage,
			AttNotNull:   notNull,
			AttHasDef:    hasDef,
			AttIsDropped: false,
			AttCollation: col.Collation,
			AttGenerated: col.Generated,
			AttIdentity:  col.Identity,
			AttIsLocal:   col.IsLocal,
			AttInhCount:  col.InhCount,
		}
	}
	return rows
}

// QueryPgType returns pg_type rows for user-created types in a schema.
//
// (pgddl helper — PG uses SearchSysCache with pg_type)
func (c *Catalog) QueryPgType(schemaName string) []PgTypeRow {
	schema := c.schemaByName[schemaName]
	if schema == nil {
		return nil
	}

	var rows []PgTypeRow
	for _, bt := range c.typeByOID {
		if bt.Namespace != schema.OID {
			continue
		}
		// Only include user-created types (OID >= FirstNormalObjectId).
		if bt.OID < FirstNormalObjectId {
			continue
		}
		rows = append(rows, PgTypeRow{
			OID:          bt.OID,
			TypName:      bt.TypeName,
			TypNamespace: bt.Namespace,
			TypLen:       bt.Len,
			TypByVal:     bt.ByVal,
			TypType:      bt.Type,
			TypCategory:  bt.Category,
			TypIsDefined: bt.IsDefined,
			TypDelim:     bt.Delim,
			TypRelID:     bt.RelID,
			TypElem:      bt.Elem,
			TypArray:     bt.Array,
			TypBaseType:  bt.BaseType,
			TypTypMod:    bt.TypeMod,
			TypAlign:     bt.Align,
			TypStorage:   bt.Storage,
			TypNotNull:   bt.NotNull,
			TypCollation: bt.Collation,
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].OID < rows[j].OID })
	return rows
}

// QueryPgConstraint returns pg_constraint rows for a relation by OID.
//
// (pgddl helper — PG uses SearchSysCache with pg_constraint)
func (c *Catalog) QueryPgConstraint(relOID uint32) []PgConstraintRow {
	var rows []PgConstraintRow
	for _, con := range c.consByRel[relOID] {
		row := PgConstraintRow{
			OID:           con.OID,
			ConName:       con.Name,
			ConNamespace:  c.constraintNamespace(con),
			ConType:       byte(con.Type),
			ConRelID:      con.RelOID,
			ConKey:        con.Columns,
			ConIndexID:    con.IndexOID,
			ConValidated:  con.Validated,
			ConDeferrable: con.Deferrable,
			ConDeferred:   con.Deferred,
			ConParentID:   con.ConParentID,
			ConIsLocal:    con.ConIsLocal,
			ConInhCount:   con.ConInhCount,
			ConNoInherit:  con.ConNoInherit,
		}

		if con.Type == ConstraintFK {
			row.ConFRelID = con.FRelOID
			row.ConFKey = con.FColumns
			row.ConFUpdType = con.FKUpdAction
			row.ConFDelType = con.FKDelAction
			row.ConFMatchType = con.FKMatchType
			row.PFEqOp = con.PFEqOp
			row.PPEqOp = con.PPEqOp
			row.FFEqOp = con.FFEqOp
			row.FKDelSetCols = con.FKDelSetCols
		}

		if con.Type == ConstraintCheck {
			// pg: pg_get_constraintdef_worker — CHECK (%s)
			// Non-pretty deparse wraps ops/boolexprs in parens, so
			// CHECK (%s) already gets the right paren nesting.
			if con.CheckAnalyzed != nil {
				rel := c.relationByOID[con.RelOID]
				if rel != nil {
					rte := c.buildRelationRTE(rel)
					exprText := c.DeparseExpr(con.CheckAnalyzed, []*RangeTableEntry{rte}, false)
					row.ConExpr = "CHECK (" + exprText + ")"
				} else {
					row.ConExpr = "CHECK ((" + con.CheckExpr + "))"
				}
			} else {
				row.ConExpr = "CHECK ((" + con.CheckExpr + "))"
			}
		}

		rows = append(rows, row)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].OID < rows[j].OID })
	return rows
}

// constraintNamespace returns the namespace OID for a constraint.
func (c *Catalog) constraintNamespace(con *Constraint) uint32 {
	if con.Namespace != 0 {
		return con.Namespace
	}
	// Derive from the owning relation.
	if rel := c.relationByOID[con.RelOID]; rel != nil && rel.Schema != nil {
		return rel.Schema.OID
	}
	return 0
}

// QueryPgIndex returns pg_index rows for a relation by OID.
//
// (pgddl helper — PG uses SearchSysCache with pg_index)
func (c *Catalog) QueryPgIndex(relOID uint32) []PgIndexRow {
	var rows []PgIndexRow
	for _, idx := range c.indexesByRel[relOID] {
		nKeyAtts := int16(idx.NKeyColumns)
		if nKeyAtts == 0 {
			nKeyAtts = int16(len(idx.Columns))
		}
		// Build indexprs: PG's pg_get_expr concatenates expression texts.
		indExprs := ""
		if len(idx.Exprs) > 0 {
			indExprs = strings.Join(idx.Exprs, ", ")
		}
		row := PgIndexRow{
			IndexRelID:     idx.OID,
			IndRelID:       idx.RelOID,
			IndNatts:       int16(len(idx.Columns)),
			IndNKeyAtts:    nKeyAtts,
			IndIsUnique:    idx.IsUnique,
			IndIsPrimary:   idx.IsPrimary,
			IndIsClustered: idx.IsClustered,
			IndIsReplIdent: idx.IsReplicaIdent,
			IndKey:         idx.Columns,
			IndOption:      idx.IndOption,
			IndExprs:       indExprs,
			IndPred:        idx.WhereClause,
		}
		rows = append(rows, row)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].IndexRelID < rows[j].IndexRelID })
	return rows
}

// QueryPgSequence returns pg_sequence rows for all sequences in a schema.
//
// (pgddl helper — PG uses SearchSysCache with pg_sequence)
func (c *Catalog) QueryPgSequence(schemaName string) []PgSequenceRow {
	schema := c.schemaByName[schemaName]
	if schema == nil {
		return nil
	}

	var rows []PgSequenceRow
	for _, seq := range schema.Sequences {
		rows = append(rows, PgSequenceRow{
			SeqRelID:     seq.OID,
			SeqTypID:     seq.TypeOID,
			SeqStart:     seq.Start,
			SeqIncrement: seq.Increment,
			SeqMax:       seq.MaxValue,
			SeqMin:       seq.MinValue,
			SeqCache:     seq.CacheValue,
			SeqCycle:     seq.Cycle,
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].SeqRelID < rows[j].SeqRelID })
	return rows
}

// QueryPgEnum returns pg_enum rows for an enum type by OID.
//
// (pgddl helper — PG uses SearchSysCache with pg_enum)
func (c *Catalog) QueryPgEnum(typeOID uint32) []PgEnumRow {
	et := c.enumTypes[typeOID]
	if et == nil {
		return nil
	}

	rows := make([]PgEnumRow, len(et.Values))
	for i, ev := range et.Values {
		rows[i] = PgEnumRow{
			OID:           ev.OID,
			EnumTypID:     ev.EnumOID,
			EnumSortOrder: ev.SortOrder,
			EnumLabel:     ev.Label,
		}
	}
	return rows
}

// QueryPgAttrdef returns pg_attrdef rows for a relation by OID.
//
// (pgddl helper — PG uses SearchSysCache with pg_attrdef)
func (c *Catalog) QueryPgAttrdef(relOID uint32) []PgAttrdefRow {
	rel := c.relationByOID[relOID]
	if rel == nil {
		return nil
	}

	var rows []PgAttrdefRow
	for _, col := range rel.Columns {
		// PG: identity columns do NOT have pg_attrdef entries;
		// identity sequence linkage is via pg_depend, not column defaults.
		// pg: src/backend/catalog/heap.c — identity handling
		if col.HasDefault && col.Identity == 0 {
			adBin := col.Default
			if col.DefaultAnalyzed != nil {
				rte := c.buildRelationRTE(rel)
				adBin = c.DeparseExpr(col.DefaultAnalyzed, []*RangeTableEntry{rte}, false)
			}
			rows = append(rows, PgAttrdefRow{
				AdRelID: relOID,
				AdNum:   col.AttNum,
				AdBin:   adBin,
			})
		}
	}
	return rows
}

// QueryPgTrigger returns pg_trigger rows for a relation by OID.
//
// (pgddl helper — PG uses SearchSysCache with pg_trigger)
func (c *Catalog) QueryPgTrigger(relOID uint32) []PgTriggerRow {
	var rows []PgTriggerRow
	for _, trig := range c.triggersByRel[relOID] {
		tgType := composeTriggerType(trig)
		tgEnabled := trig.Enabled
		if tgEnabled == 0 {
			tgEnabled = 'O' // default if not set
		}

		rows = append(rows, PgTriggerRow{
			OID:        trig.OID,
			TgRelID:    trig.RelOID,
			TgName:     trig.Name,
			TgFOID:     trig.FuncOID,
			TgType:     tgType,
			TgEnabled:  tgEnabled,
			TgAttr:     trig.Columns,
			TgQual:     trig.WhenExpr,
			TgOldTable: trig.OldTransitionName,
			TgNewTable: trig.NewTransitionName,
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].OID < rows[j].OID })
	return rows
}

// composeTriggerType builds the tgtype bitmask from trigger properties.
// pg: src/include/catalog/pg_trigger.h
func composeTriggerType(trig *Trigger) int16 {
	var tgtype int16
	if trig.ForEachRow {
		tgtype |= 1 // TRIGGER_TYPE_ROW
	}
	switch trig.Timing {
	case TriggerBefore:
		tgtype |= 2 // TRIGGER_TYPE_BEFORE
	case TriggerInsteadOf:
		tgtype |= 64 // TRIGGER_TYPE_INSTEAD
	default:
		// AFTER: bit not set (0 in the timing bits means AFTER)
	}
	if trig.Events&TriggerEventInsert != 0 {
		tgtype |= 4 // TRIGGER_TYPE_INSERT
	}
	if trig.Events&TriggerEventDelete != 0 {
		tgtype |= 8 // TRIGGER_TYPE_DELETE
	}
	if trig.Events&TriggerEventUpdate != 0 {
		tgtype |= 16 // TRIGGER_TYPE_UPDATE
	}
	if trig.Events&TriggerEventTruncate != 0 {
		tgtype |= 32 // TRIGGER_TYPE_TRUNCATE
	}
	return tgtype
}

// QueryPgProc returns pg_proc rows for user-created functions in a schema.
//
// (pgddl helper — PG uses SearchSysCache with pg_proc)
func (c *Catalog) QueryPgProc(schemaName string) []PgProcRow {
	schema := c.schemaByName[schemaName]
	if schema == nil {
		return nil
	}

	var rows []PgProcRow
	for _, up := range c.userProcs {
		if up.Schema.OID != schema.OID {
			continue
		}
		rows = append(rows, PgProcRow{
			OID:             up.OID,
			ProName:         up.Name,
			ProNamespace:    schema.OID,
			ProKind:         up.Kind,
			ProArgTypes:     up.ArgTypes,
			ProRetType:      up.RetType,
			ProRetSet:       up.RetSet,
			ProIsStrict:     up.IsStrict,
			ProVolatile:     up.Volatile,
			ProParallel:     up.Parallel,
			ProSecDef:       up.SecDef,
			ProLeakProof:    up.LeakProof,
			ProLang:         up.Language,
			ProSrc:          up.Body,
			ProArgNames:     up.ArgNames,
			ProArgModes:     up.ArgModes,
			ProAllArgTypes:  up.AllArgTypes,
			ProNArgDefaults: up.NArgDefaults,
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].OID < rows[j].OID })
	return rows
}

// QueryPgDescription returns all pg_description rows.
//
// (pgddl helper — PG uses SearchSysCache with pg_description)
func (c *Catalog) QueryPgDescription() []PgDescriptionRow {
	var rows []PgDescriptionRow
	for key, desc := range c.comments {
		rows = append(rows, PgDescriptionRow{
			ObjOID:      key.ObjOID,
			ClassOID:    objTypeToClassOID(key.ObjType),
			ObjSubID:    key.SubID,
			Description: desc,
		})
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].ClassOID != rows[j].ClassOID {
			return rows[i].ClassOID < rows[j].ClassOID
		}
		if rows[i].ObjOID != rows[j].ObjOID {
			return rows[i].ObjOID < rows[j].ObjOID
		}
		return rows[i].ObjSubID < rows[j].ObjSubID
	})
	return rows
}

// QueryPgDepend returns all pg_depend rows.
//
// (pgddl helper — PG uses SearchSysCache with pg_depend)
func (c *Catalog) QueryPgDepend() []PgDependRow {
	rows := make([]PgDependRow, len(c.deps))
	for i, dep := range c.deps {
		rows[i] = PgDependRow{
			ClassID:    objTypeToClassOID(dep.ObjType),
			ObjID:      dep.ObjOID,
			ObjSubID:   dep.ObjSubID,
			RefClassID: objTypeToClassOID(dep.RefType),
			RefObjID:   dep.RefOID,
			RefSubID:   dep.RefSubID,
			DepType:    byte(dep.DepType),
		}
	}
	return rows
}

// QueryPgInherits returns all pg_inherits rows.
//
// (pgddl helper — PG uses SearchSysCache with pg_inherits)
func (c *Catalog) QueryPgInherits() []PgInheritsRow {
	rows := make([]PgInheritsRow, len(c.inhEntries))
	for i, e := range c.inhEntries {
		rows[i] = PgInheritsRow{
			InhRelID:  e.InhRelID,
			InhParent: e.InhParent,
			InhSeqNo:  e.InhSeqNo,
		}
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].InhRelID != rows[j].InhRelID {
			return rows[i].InhRelID < rows[j].InhRelID
		}
		return rows[i].InhSeqNo < rows[j].InhSeqNo
	})
	return rows
}

// PgPolicyRow mirrors pg_policy.
type PgPolicyRow struct {
	OID        uint32
	PolName    string
	PolRelID   uint32
	PolCmd     string // "all", "select", "insert", "update", "delete"
	Permissive bool
	Roles      []string
	PolQual    string // USING expression
	PolCheck   string // WITH CHECK expression
}

// QueryPgPolicy returns pg_policy rows for the given relation OID.
// If relOID is 0, returns all policies.
//
// pg: src/include/catalog/pg_policy.h
func (c *Catalog) QueryPgPolicy(relOID uint32) []PgPolicyRow {
	var rows []PgPolicyRow
	var policies []*Policy
	if relOID != 0 {
		policies = c.policiesByRel[relOID]
	} else {
		for _, p := range c.policies {
			policies = append(policies, p)
		}
	}
	for _, p := range policies {
		polQual := p.UsingExpr
		polCheck := p.CheckExpr
		if p.UsingAnalyzed != nil || p.CheckAnalyzed != nil {
			rel := c.relationByOID[p.RelOID]
			if rel != nil {
				rte := c.buildRelationRTE(rel)
				rtable := []*RangeTableEntry{rte}
				if p.UsingAnalyzed != nil {
					polQual = c.DeparseExpr(p.UsingAnalyzed, rtable, false)
				}
				if p.CheckAnalyzed != nil {
					polCheck = c.DeparseExpr(p.CheckAnalyzed, rtable, false)
				}
			}
		}
		rows = append(rows, PgPolicyRow{
			OID:        p.OID,
			PolName:    p.Name,
			PolRelID:   p.RelOID,
			PolCmd:     p.CmdType,
			Permissive: p.Permissive,
			Roles:      p.Roles,
			PolQual:    polQual,
			PolCheck:   polCheck,
		})
	}
	sort.Slice(rows, func(i, j int) bool {
		return rows[i].OID < rows[j].OID
	})
	return rows
}

// PgDomainConstraintRow mirrors a domain CHECK constraint as visible through pg_constraint.
type PgDomainConstraintRow struct {
	DomainName   string
	ConName      string
	ConDef       string // CHECK ((expr)) form
	ConValidated bool
}

// GetDomainConstraintByOID returns the name of a domain constraint by its OID,
// or empty string if not found.
//
// (pgddl helper — PG uses SearchSysCache1(CONSTROID, ...))
func (c *Catalog) GetDomainConstraintByOID(oid uint32) string {
	for _, dt := range c.domainTypes {
		for _, dc := range dt.Constraints {
			if dc.OID == oid {
				return dc.Name
			}
		}
	}
	return ""
}

// QueryPgDomainConstraints returns domain CHECK constraints for a given schema.
//
// (pgddl helper — PG uses pg_constraint with contypid != 0)
func (c *Catalog) QueryPgDomainConstraints(schemaName string) []PgDomainConstraintRow {
	schema := c.schemaByName[schemaName]
	if schema == nil {
		return nil
	}

	var rows []PgDomainConstraintRow
	for oid, dt := range c.domainTypes {
		bt := c.typeByOID[oid]
		if bt == nil || bt.Namespace != schema.OID {
			continue
		}
		// pg: PG17+ creates a contype='n' constraint row for domain NOT NULL.
		// pg: src/backend/commands/typecmds.c — DefineDomain (NOT NULL handling)
		if dt.NotNull {
			rows = append(rows, PgDomainConstraintRow{
				DomainName:   bt.TypeName,
				ConName:      bt.TypeName + "_not_null",
				ConDef:       "NOT NULL",
				ConValidated: true,
			})
		}
		for _, dc := range dt.Constraints {
			var conDef string
			if dc.CheckAnalyzed != nil {
				// pg: pg_get_constraintdef(oid, true) — pretty with PRETTYFLAG_PAREN
				// CoerceToDomainValueExpr deparses as "VALUE" directly.
				exprText := c.DeparseExpr(dc.CheckAnalyzed, nil, true)
				conDef = "CHECK (" + exprText + ")"
			} else {
				conDef = "CHECK ((" + dc.CheckExpr + "))"
			}
			rows = append(rows, PgDomainConstraintRow{
				DomainName:   bt.TypeName,
				ConName:      dc.Name,
				ConDef:       conDef,
				ConValidated: dc.ConValidated,
			})
		}
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].DomainName != rows[j].DomainName {
			return rows[i].DomainName < rows[j].DomainName
		}
		return rows[i].ConName < rows[j].ConName
	})
	return rows
}

// objTypeToClassOID maps internal object type chars to pg_class OIDs.
func objTypeToClassOID(objType byte) uint32 {
	switch objType {
	case 'r': // relation (table, view)
		return RelationRelationID
	case 'i': // index
		return RelationRelationID // indexes are in pg_class too
	case 'c': // constraint
		return ConstraintRelationID
	case 't': // type
		return TypeRelationID
	case 'f': // function/procedure
		return ProcedureRelationID
	case 'g': // trigger
		return TriggerRelationID
	case 'n': // namespace/schema
		return NamespaceRelationID
	case 's': // sequence
		return RelationRelationID // sequences are in pg_class too
	default:
		return 0
	}
}
