-- Statement: ALTER PARTITION SCHEME
-- Grammar rule: alterPartitionSchemeStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-partition-scheme-transact-sql

-- From TSql170.g:
alterPartitionSchemeStatement:
    Identifier /* SCHEME */ identifier
    Identifier /* NEXT */ Identifier /* USED */
    ( stringOrIdentifier )?
    ;

-- Note: reached via alterPartitionStatement:
-- alterPartitionStatement:
--     Identifier /* PARTITION */
--     ( alterPartitionFunctionStatement | alterPartitionSchemeStatement )
--     ;

-- From Microsoft docs:
ALTER PARTITION SCHEME partition_scheme_name
NEXT USED [ filegroup_name ] [ ; ]
