-- Statement: ALTER XML SCHEMA COLLECTION
-- Grammar rule: alterXmlSchemaCollectionStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-xml-schema-collection-transact-sql

-- From TSql170.g:
alterXmlSchemaCollectionStatement:
    -- Context: ALTER already consumed
    XML SCHEMA COLLECTION vSchemaObjectName = schemaObjectNonEmptyTwoPartName
    ADD vExpression = expression
    ;

-- From Microsoft docs:
-- ALTER XML SCHEMA COLLECTION [ relational_schema. ]sql_identifier ADD 'Schema Component'
