-- Statement: CREATE BROKER PRIORITY
-- Grammar rule: createBrokerPriorityStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/statements/create-broker-priority-transact-sql

-- From TSql170.g:
createBrokerPriorityStatement:
    brokerPriorityStatementBody[vResult]
    ;

brokerPriorityStatementBody[BrokerPriorityStatement vParent]:
    tBroker:Identifier tPriority:Identifier vIdentifier=identifier
    tFor:For tForClause:Identifier   -- FOR CONVERSATION
    (
        options {greedy = true; } :
        tSet:Set
        LeftParenthesis vBrokerPriorityParameter = brokerPriorityParameter[encounteredOptions]
        (tComma:Comma vBrokerPriorityParameter = brokerPriorityParameter[encounteredOptions]
        )*
        tRParen:RightParenthesis
    )?
    ;

brokerPriorityParameter[int encountered]:
    tParameter:Identifier
    -- CONTRACT_NAME | LOCAL_SERVICE_NAME | REMOTE_SERVICE_NAME | PRIORITY_LEVEL
    EqualsSign
    (
        vParameter1=identifier           -- for CONTRACT_NAME, LOCAL_SERVICE_NAME
        | vParameter2=stringLiteral      -- for REMOTE_SERVICE_NAME
        | vParameter=integer             -- for PRIORITY_LEVEL (1-10)
        | tDefault:Default               -- for PRIORITY_LEVEL = DEFAULT
        | tAny:Any                       -- for CONTRACT_NAME, LOCAL_SERVICE_NAME, REMOTE_SERVICE_NAME = ANY
    )
    ;

-- From Microsoft docs:
CREATE BROKER PRIORITY ConversationPriorityName
FOR CONVERSATION
[ SET ( [ CONTRACT_NAME = {ContractName | ANY } ]
        [ [ , ] LOCAL_SERVICE_NAME = {LocalServiceName | ANY } ]
        [ [ , ] REMOTE_SERVICE_NAME = {'RemoteServiceName' | ANY } ]
        [ [ , ] PRIORITY_LEVEL = {PriorityValue | DEFAULT } ]
       )
]
[;]
