-- Statement: CREATE SYNONYM
-- Grammar rule: createSynonymStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/statements/create-synonym-transact-sql

-- From TSql170.g:
createSynonymStatement:
    SYNONYM schemaObjectThreePartName
    FOR schemaObjectFourPartName
    ;

-- From Microsoft docs:
CREATE SYNONYM [ schema_name_1. ] synonym_name FOR <object>

<object> ::=
{
    [
        server_name. [ database_name ] . [ schema_name_2 ] .
        | database_name. [ schema_name_2 ] .
        | schema_name_2.
    ]
    object_name
}
