-- Statement: DROP FULLTEXT STOPLIST
-- Grammar rule: dropFulltextStoplistStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-fulltext-stoplist-transact-sql

-- From TSql170.g:
-- (dispatched via dropFulltextStatements after matching DROP FULLTEXT)

dropFulltextStoplistStatement:
    StopList identifier
    requiredSemicolon
    ;

-- From Microsoft docs:
DROP FULLTEXT STOPLIST stoplist_name
;
