-- Statement: DROP COLUMN MASTER KEY
-- Grammar rule: dropColumnMasterKeyStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-column-master-key-transact-sql

-- From TSql170.g:
dropColumnMasterKeyStatement:
    -- Note: DROP COLUMN is parsed by the dispatcher; this rule handles MASTER KEY <name>
    Master Key identifier
    ;

-- Sub-rules:
-- (none beyond identifier)

-- From Microsoft docs:
DROP COLUMN MASTER KEY key_name;
