-- Statement: DROP QUEUE
-- Grammar rule: dropQueueStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-queue-transact-sql

-- From TSql170.g:
dropQueueStatement:
    DROP QUEUE schema_object_name
    ;

-- Sub-rules:
-- schema_object_name = schemaObjectThreePartName
--   i.e. { database_name.schema_name.queue_name | schema_name.queue_name | queue_name }

-- From Microsoft docs:
DROP QUEUE <object>
[ ; ]

<object> ::=
{ database_name.schema_name.queue_name | schema_name.queue_name | queue_name }
