-- Statement: RECONFIGURE
-- Grammar rule: reconfigureStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/reconfigure-transact-sql

-- From TSql170.g:
reconfigureStatement:
    Reconfigure
    ( With Identifier /* OVERRIDE */ )?
    ;

-- From Microsoft docs:
RECONFIGURE [ WITH OVERRIDE ]
