-- Statement: SET VARIABLE
-- Grammar rule: setVariableStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/set-local-variable-transact-sql

-- From TSql170.g:
setVariableStatement:
    variable
    (
        (Dot | DoubleColon) identifier
        (
            parenthesizedOptExpressionWithDefaultList  /* method call */
        |
            assignmentWithOptOp expression
        )
    |
        (
            assignmentWithOptOp expression
        |
            EqualsSign cursorDefinition
        )
    )
    ;

assignmentWithOptOp:
    /* =, +=, -=, *=, /=, %=, &=, ^=, |= */
    EqualsSign
    | AddEquals | SubtractEquals | MultiplyEquals | DivideEquals
    | ModuleEquals | BitwiseAndEquals | BitwiseOrEquals | BitwiseXorEquals
    ;

-- From Microsoft docs:

-- SQL Server / Azure SQL Database Syntax:
SET
{ @local_variable
    [ . { property_name | field_name } ] = { expression | udt_name { . | :: } method_name }
}
| { @SQLCLR_local_variable.mutator_method }
| { @local_variable
    { += | -= | *= | /= | %= | &= | ^= | |= } expression
}
| { @cursor_variable =
    { @cursor_variable | cursor_name
    | { CURSOR [ [ LOCAL | GLOBAL ] ]
        [ FORWARD_ONLY | SCROLL ]
        [ STATIC | KEYSET | DYNAMIC | FAST_FORWARD ]
        [ READ_ONLY | SCROLL_LOCKS | OPTIMISTIC ]
        [ TYPE_WARNING ]
    FOR select_statement
        [ FOR { READ ONLY | UPDATE [ OF column_name [ ,...n ] ] } ]
      }
    }
}

-- Azure Synapse / PDW / Fabric Syntax:
SET @local_variable { = | += | -= | *= | /= | %= | &= | ^= | |= } expression
