-- Statement: SET TEXTSIZE
-- Grammar rule: setTextSizeStatement (TSql170.g)
-- Doc: https://learn.microsoft.com/en-us/sql/t-sql/statements/set-textsize-transact-sql

-- From TSql170.g:
setTextSizeStatement:
    TextSize signedInteger
    ;

-- Sub-rules:

signedInteger:
    (Minus)? Integer
    ;

-- From Microsoft docs:
-- SET TEXTSIZE { number }
--
-- number is the length of varchar(max), nvarchar(max), varbinary(max),
-- text, ntext, or image data, in bytes.
-- Maximum value is 2147483647 (2 GB).
-- A value of -1 indicates unlimited size.
-- A value of 0 resets the size to the default value of 4 KB.
