-- Statement: ALTER OUTLINE
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/ALTER-OUTLINE.html

ALTER OUTLINE [ PUBLIC | PRIVATE ] outline
    { REBUILD
    | RENAME TO new_outline_name
    | CHANGE CATEGORY TO new_category_name
    | { ENABLE | DISABLE }
    } ;
