-- Statement: CREATE SYNONYM
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/CREATE-SYNONYM.html

CREATE [ OR REPLACE | IF NOT EXISTS ]
    [ EDITIONABLE | NONEDITIONABLE ]
    [ PUBLIC ] SYNONYM [ schema. ] synonym
    [ SHARING = { METADATA | NONE } ]
    FOR [ schema. ] object [ @ dblink ] ;
