-- Statement: CREATE CONTROLFILE
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/CREATE-CONTROLFILE.html

CREATE CONTROLFILE
    [ REUSE ]
    { SET DATABASE database | DATABASE database }
    logfile_clause
    [ { RESETLOGS | NORESETLOGS } ]
    [ DATAFILE file_specification [, file_specification ]... ]
    [ MAXLOGFILES integer ]
    [ MAXLOGMEMBERS integer ]
    [ MAXLOGHISTORY integer ]
    [ MAXDATAFILES integer ]
    [ MAXINSTANCES integer ]
    [ { ARCHIVELOG | NOARCHIVELOG } ]
    [ FORCE LOGGING ]
    [ SET STANDBY NOLOGGING FOR { DATA AVAILABILITY | LOAD PERFORMANCE } ]
    [ character_set_clause ] ;

logfile_clause:
    LOGFILE
    [ GROUP integer ] file_specification [, [ GROUP integer ] file_specification ]...

character_set_clause:
    CHARACTER SET character_set
