-- Statement: CREATE INDEX
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/CREATE-INDEX.html

CREATE [ UNIQUE ] [ BITMAP ] [ MULTIVALUE ] INDEX [ IF NOT EXISTS ]
    [ schema. ] index_name
    [ index_ilm_clause ]
    { cluster_index_clause | table_index_clause | bitmap_join_index_clause }
    [ { DEFERRED | IMMEDIATE } INVALIDATION ] ;

cluster_index_clause:
    ON CLUSTER [ schema. ] cluster
    [ index_attributes ]

table_index_clause:
    ON [ schema. ] table [ t_alias ]
    ( index_expr [ ASC | DESC ] [, index_expr [ ASC | DESC ] ]... )
    [ index_properties ]

index_expr:
    { column | column_expression }

index_properties:
    [ global_partitioned_index | local_partitioned_index ]
    [ index_attributes ]
    [ domain_index_clause | XMLIndex_clause ]

global_partitioned_index:
    GLOBAL PARTITION BY
    { RANGE ( column_list )
        ( index_partitioning_clause [, index_partitioning_clause ]... )
    | HASH ( column_list )
        { individual_hash_partitions | hash_partitions_by_quantity } }

index_partitioning_clause:
    PARTITION [ partition_name ]
        VALUES LESS THAN ( value_list )
        [ segment_attributes_clause ]

individual_hash_partitions:
    ( PARTITION [ partition_name ] [ partitioning_storage_clause ]
      [, PARTITION [ partition_name ] [ partitioning_storage_clause ] ]... )

hash_partitions_by_quantity:
    PARTITIONS integer
    [ STORE IN ( tablespace [, tablespace ]... ) ]

local_partitioned_index:
    LOCAL
    [ on_range_partitioned_table
    | on_list_partitioned_table
    | on_hash_partitioned_table
    | on_comp_partitioned_table ]

on_range_partitioned_table:
    ( PARTITION [ partition_name ]
        [ segment_attributes_clause ]
        [ index_compression ]
        [ { USABLE | UNUSABLE } ]
      [, PARTITION [ partition_name ]
        [ segment_attributes_clause ]
        [ index_compression ]
        [ { USABLE | UNUSABLE } ] ]... )

on_list_partitioned_table:
    ( PARTITION [ partition_name ]
        [ segment_attributes_clause ]
        [ index_compression ]
        [ { USABLE | UNUSABLE } ]
      [, PARTITION [ partition_name ]
        [ segment_attributes_clause ]
        [ index_compression ]
        [ { USABLE | UNUSABLE } ] ]... )

on_hash_partitioned_table:
    [ ( PARTITION [ partition_name ]
          [ TABLESPACE tablespace ]
          [ index_compression ]
          [ { USABLE | UNUSABLE } ]
        [, PARTITION [ partition_name ]
          [ TABLESPACE tablespace ]
          [ index_compression ]
          [ { USABLE | UNUSABLE } ] ]... ) ]
    [ STORE IN ( tablespace [, tablespace ]... ) ]

on_comp_partitioned_table:
    ( PARTITION [ partition_name ]
        [ segment_attributes_clause ]
        [ index_compression ]
        [ index_subpartition_clause ]
        [ { USABLE | UNUSABLE } ]
      [, PARTITION [ partition_name ]
        [ segment_attributes_clause ]
        [ index_compression ]
        [ index_subpartition_clause ]
        [ { USABLE | UNUSABLE } ] ]... )

index_subpartition_clause:
    ( SUBPARTITION [ subpartition_name ]
        [ TABLESPACE tablespace ]
        [ index_compression ]
        [ { USABLE | UNUSABLE } ]
      [, SUBPARTITION [ subpartition_name ]
        [ TABLESPACE tablespace ]
        [ index_compression ]
        [ { USABLE | UNUSABLE } ] ]... )
    | STORE IN ( tablespace [, tablespace ]... )

index_attributes:
    [ physical_attributes_clause ]
    [ TABLESPACE { tablespace | DEFAULT } ]
    [ index_compression ]
    [ partial_index_clause ]
    [ parallel_clause ]
    [ { SORT | NOSORT } ]
    [ REVERSE ]
    [ { VISIBLE | INVISIBLE } ]
    [ logging_clause ]
    [ ONLINE ]
    [ annotations_clause ]

physical_attributes_clause:
    [ PCTFREE integer ]
    [ INITRANS integer ]
    [ MAXTRANS integer ]
    [ storage_clause ]

index_compression:
    { prefix_compression | advanced_index_compression }

prefix_compression:
    COMPRESS [ integer ] | NOCOMPRESS

advanced_index_compression:
    COMPRESS ADVANCED [ LOW | HIGH ] | NOCOMPRESS

partial_index_clause:
    INDEXING { FULL | PARTIAL }

parallel_clause:
    { PARALLEL [ integer ] | NOPARALLEL }

logging_clause:
    { LOGGING | NOLOGGING }

domain_index_clause:
    INDEXTYPE IS [ schema. ] indextype
    [ local_domain_index_clause ]
    [ parallel_clause ]
    [ PARAMETERS ( 'parameter_string' ) ]

local_domain_index_clause:
    LOCAL
    [ ( PARTITION [ partition_name ] [ PARAMETERS ( 'parameter_string' ) ]
        [, PARTITION [ partition_name ] [ PARAMETERS ( 'parameter_string' ) ] ]... ) ]

XMLIndex_clause:
    INDEXTYPE IS XDB.XMLINDEX
    [ local_xmlindex_clause ]
    [ parallel_clause ]
    [ PARAMETERS ( 'XMLIndex_parameters_clause' ) ]

local_xmlindex_clause:
    LOCAL
    [ ( PARTITION [ partition_name ] [ PARAMETERS ( 'XMLIndex_parameters_clause' ) ]
        [, PARTITION [ partition_name ] [ PARAMETERS ( 'XMLIndex_parameters_clause' ) ] ]... ) ]

bitmap_join_index_clause:
    ON [ schema. ] table
    ( [ schema. ] table . column
      [, [ schema. ] table . column ]... )
    FROM [ schema. ] table [, [ schema. ] table ]...
    WHERE join_condition
    [ local_partitioned_index ]
    [ index_attributes ]

segment_attributes_clause:
    [ physical_attributes_clause ]
    [ TABLESPACE { tablespace | DEFAULT } ]
    [ logging_clause ]

partitioning_storage_clause:
    [ TABLESPACE tablespace ]
    [ index_compression ]
