-- Statement: DROP RESTORE POINT
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/DROP-RESTORE-POINT.html

DROP RESTORE POINT restore_point
    [ FOR PLUGGABLE DATABASE pdb_name ] ;
