-- Statement: DROP MATERIALIZED VIEW
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/DROP-MATERIALIZED-VIEW.html

DROP MATERIALIZED VIEW [ IF EXISTS ] [ schema. ] materialized_view_name
    [ PRESERVE TABLE ] ;
