-- Statement: DROP INDEX
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/DROP-INDEX.html

DROP INDEX [ IF EXISTS ] [ schema. ] index_name
    [ ONLINE ]
    [ FORCE ]
    [ { DEFERRED | IMMEDIATE } INVALIDATION ] ;
