-- Statement: DROP MATERIALIZED ZONEMAP
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/DROP-MATERIALIZED-ZONEMAP.html

DROP MATERIALIZED ZONEMAP [ IF EXISTS ] [ schema. ] zonemap_name ;
