-- Statement: DROP INMEMORY JOIN GROUP
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/DROP-INMEMORY-JOIN-GROUP.html

DROP INMEMORY JOIN GROUP [ IF EXISTS ] [ schema. ] join_group_name ;
