-- Statement: MERGE
-- Source: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/MERGE.html

MERGE [ hint ] INTO [ schema. ] { table | view } [ t_alias ]
    USING { [ schema. ] { table | view }
          | subquery
          } [ t_alias ]
    ON ( condition )
    [ merge_update_clause ]
    [ merge_insert_clause ]
    [ error_logging_clause ] ;

merge_update_clause::=
    WHEN MATCHED THEN
    UPDATE SET column = { expr | DEFAULT }
               [, column = { expr | DEFAULT } ]...
    [ WHERE condition ]
    [ DELETE WHERE condition ]

merge_insert_clause::=
    WHEN NOT MATCHED THEN
    INSERT [ ( column [, column ]... ) ]
    VALUES ( { expr | DEFAULT } [, { expr | DEFAULT } ]... )
    [ WHERE condition ]

error_logging_clause::=
    LOG ERRORS [ INTO [ schema. ] table ]
    [ ( simple_expression ) ]
    [ REJECT LIMIT { integer | UNLIMITED } ]
